name: Deploy

on: [push]
# push:
#   branches:
#     - master
#     - main
# pull_request:
#   branches:
#     - master
#     - main
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install node dependencies
        run: npm install

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm build
        
      - name: Setup deploy options
        id: setup
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [[ ${GITHUB_REF} = refs/pull/*/merge ]]; then # pull request
            echo "::set-output name=SRC_BRANCH::${GITHUB_HEAD_REF}"
            echo "::set-output name=NO_PUSH::--no-push"
          elif [[ ${GITHUB_REF} = refs/heads/* ]]; then # branch, e.g. master, source etc
            echo "::set-output name=SRC_BRANCH::${GITHUB_REF#refs/heads/}"
          fi
          echo "::set-output name=DEPLOY_BRANCH::gh-pages"
      - name: Deploy website 
        run:  yes | bin/deploy --src master
                      --deploy gh-pages


    